### PR TITLE
Add CC0 to valid licences

### PR DESCRIPTION
**Pull request by Moth-Tolias**
closes dlang/dub-registry#537

### CODE REVIEW

**Comment by Moth-Tolias** [comment]
i'm not sure why the checks failed, the log doesn't want to load...

**Comment by WebFreak001** [comment]
build log (doesn't seem to load when unauthenticated):
```
3:35:26 PM: Build ready to start
3:35:30 PM: build-image version: d55944c047ef0aee2ac01971edde72cb2a50acfe (focal)
3:35:30 PM: build-image tag: v4.16.1
3:35:30 PM: buildbot version: 33f88475bcf3426608b49b7681d295235efb41f1
3:35:30 PM: Fetching cached dependencies
3:35:30 PM: Failed to fetch cache, continuing with build
3:35:30 PM: Starting to prepare the repo for build
3:35:30 PM: No cached dependencies found. Cloning fresh repo
3:35:30 PM: git clone https://github.com/dlang/dub-docs
3:35:31 PM: Preparing Git Reference pull/47/head
3:35:31 PM: Parsing package.json dependencies
3:35:32 PM: Starting build script
3:35:32 PM: Installing dependencies
3:35:32 PM: Python version set to 2.7
3:35:33 PM: v16.19.0 is already installed.
3:35:33 PM: Now using node v16.19.0 (npm v8.19.3)
3:35:33 PM: Enabling node corepack
3:35:33 PM: Started restoring cached build plugins
3:35:33 PM: Finished restoring cached build plugins
3:35:33 PM: Attempting ruby version 2.7.2, read from environment
3:35:34 PM: Using ruby version 2.7.2
3:35:34 PM: Using PHP version 8.0
3:35:34 PM: Started restoring cached go cache
3:35:34 PM: Finished restoring cached go cache
3:35:34 PM: Installing Go version 1.16.5 (requested 1.16.5)
3:35:38 PM: unset GOOS;
3:35:38 PM: unset GOARCH;
3:35:38 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64';
3:35:38 PM: export PATH="/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64/bin:${PATH}";
3:35:38 PM: go version >&2;
3:35:38 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.16.5.linux.amd64.env"
3:35:38 PM: go version go1.16.5 linux/amd64
3:35:38 PM: Detected 0 framework(s)
3:35:38 PM: Installing missing commands
3:35:38 PM: Verify run directory
3:35:38 PM: Section completed: initializing
3:35:39 PM: ​
3:35:39 PM:   Netlify Build                                                 
3:35:39 PM: ────────────────────────────────────────────────────────────────
3:35:39 PM: ​
3:35:39 PM: ❯ Version
3:35:39 PM:   @netlify/build 29.2.1
3:35:39 PM: ​
3:35:39 PM: ❯ Flags
3:35:39 PM:   baseRelDir: true
3:35:39 PM:   buildId: 63a5bcae49606e0008d70e42
3:35:39 PM:   deployId: 63a5bcae49606e0008d70e44
3:35:39 PM: ​
3:35:39 PM: ❯ Current directory
3:35:39 PM:   /opt/build/repo
3:35:39 PM: ​
3:35:39 PM: ❯ Config file
3:35:39 PM:   /opt/build/repo/netlify.toml
3:35:39 PM: ​
3:35:39 PM: ❯ Context
3:35:39 PM:   deploy-preview
3:35:39 PM: ​
3:35:39 PM:   1. build.command from netlify.toml                            
3:35:39 PM: ────────────────────────────────────────────────────────────────
3:35:39 PM: ​
3:35:39 PM: $ bash netlify.sh
3:35:39 PM: + DMD_VERSION=2.085.0
3:35:39 PM: + BUILD_DIR=out
3:35:39 PM: + CURL_FLAGS=(-fsSL --retry 10 --retry-delay 30 --retry-max-time 600 --connect-timeout 5 --speed-time 30 --speed-limit 1024)
3:35:39 PM: +++ dirname netlify.sh
3:35:39 PM: ++ cd .
3:35:39 PM: ++ pwd
3:35:39 PM: + DIR=/opt/build/repo
3:35:39 PM: + cd /opt/build/repo
3:35:39 PM: ++ curl -fsSL --retry 10 --retry-delay 30 --retry-max-time 600 --connect-timeout 5 --speed-time 30 --speed-limit 1024 https://dlang.org/install.sh
3:35:39 PM: ++ bash -s install dmd-2.085.0 --activate
3:35:44 PM: + . /opt/buildhome/dlang/dmd-2.085.0/activate
3:35:44 PM: ++ '[' '!' -z ']'
3:35:44 PM: ++ _OLD_D_PATH=/opt/build/repo/node_modules/.bin:/opt/build/node_modules/.bin:/opt/node_modules/.bin:/node_modules/.bin:/opt/buildhome/.nvm/versions/node/v16.19.0/bin:/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64/bin:/opt/buildhome/.rvm/gems/ruby-2.7.2/bin:/opt/buildhome/.rvm/gems/ruby-2.7.2@global/bin:/opt/buildhome/.rvm/rubies/ruby-2.7.2/bin:/opt/buildhome/.rvm/bin:/opt/buildhome/.nvm/versions/node/v16.19.0/bin:/opt/buildhome/python2.7/bin:/home/linuxbrew/.linuxbrew/bin:/opt/buildhome/.swiftenv/bin:/opt/buildhome/.swiftenv/shims:/opt/buildhome/.php:/opt/buildhome/.binrc/bin:/opt/buildhome/.deno/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/buildhome/.cask/bin:/opt/buildhome/.gimme/bin:/opt/buildhome/.dotnet/tools:/opt/buildhome/.dotnet:/opt/buildhome/.cargo/bin
3:35:44 PM: ++ _OLD_D_LIBRARY_PATH=
3:35:44 PM: ++ _OLD_D_LD_LIBRARY_PATH=
3:35:44 PM: ++ export LIBRARY_PATH=/opt/buildhome/dlang/dmd-2.085.0/linux/lib64
3:35:44 PM: ++ LIBRARY_PATH=/opt/buildhome/dlang/dmd-2.085.0/linux/lib64
3:35:44 PM: ++ export LD_LIBRARY_PATH=/opt/buildhome/dlang/dmd-2.085.0/linux/lib64
3:35:44 PM: ++ LD_LIBRARY_PATH=/opt/buildhome/dlang/dmd-2.085.0/linux/lib64
3:35:44 PM: ++ _OLD_D_PATH=/opt/build/repo/node_modules/.bin:/opt/build/node_modules/.bin:/opt/node_modules/.bin:/node_modules/.bin:/opt/buildhome/.nvm/versions/node/v16.19.0/bin:/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64/bin:/opt/buildhome/.rvm/gems/ruby-2.7.2/bin:/opt/buildhome/.rvm/gems/ruby-2.7.2@global/bin:/opt/buildhome/.rvm/rubies/ruby-2.7.2/bin:/opt/buildhome/.rvm/bin:/opt/buildhome/.nvm/versions/node/v16.19.0/bin:/opt/buildhome/python2.7/bin:/home/linuxbrew/.linuxbrew/bin:/opt/buildhome/.swiftenv/bin:/opt/buildhome/.swiftenv/shims:/opt/buildhome/.php:/opt/buildhome/.binrc/bin:/opt/buildhome/.deno/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/buildhome/.cask/bin:/opt/buildhome/.gimme/bin:/opt/buildhome/.dotnet/tools:/opt/buildhome/.dotnet:/opt/buildhome/.cargo/bin
3:35:44 PM: ++ _OLD_D_PS1=
3:35:44 PM: ++ export 'PS1=(dmd-2.085.0)'
3:35:44 PM: ++ PS1='(dmd-2.085.0)'
3:35:44 PM: ++ export PATH=/opt/buildhome/dlang/dmd-2.085.0/linux/bin64:/opt/build/repo/node_modules/.bin:/opt/build/node_modules/.bin:/opt/node_modules/.bin:/node_modules/.bin:/opt/buildhome/.nvm/versions/node/v16.19.0/bin:/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64/bin:/opt/buildhome/.rvm/gems/ruby-2.7.2/bin:/opt/buildhome/.rvm/gems/ruby-2.7.2@global/bin:/opt/buildhome/.rvm/rubies/ruby-2.7.2/bin:/opt/buildhome/.rvm/bin:/opt/buildhome/.nvm/versions/node/v16.19.0/bin:/opt/buildhome/python2.7/bin:/home/linuxbrew/.linuxbrew/bin:/opt/buildhome/.swiftenv/bin:/opt/buildhome/.swiftenv/shims:/opt/buildhome/.php:/opt/buildhome/.binrc/bin:/opt/buildhome/.deno/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/buildhome/.cask/bin:/opt/buildhome/.gimme/bin:/opt/buildhome/.dotnet/tools:/opt/buildhome/.dotnet:/opt/buildhome/.cargo/bin
3:35:44 PM: ++ PATH=/opt/buildhome/dlang/dmd-2.085.0/linux/bin64:/opt/build/repo/node_modules/.bin:/opt/build/node_modules/.bin:/opt/node_modules/.bin:/node_modules/.bin:/opt/buildhome/.nvm/versions/node/v16.19.0/bin:/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64/bin:/opt/buildhome/.rvm/gems/ruby-2.7.2/bin:/opt/buildhome/.rvm/gems/ruby-2.7.2@global/bin:/opt/buildhome/.rvm/rubies/ruby-2.7.2/bin:/opt/buildhome/.rvm/bin:/opt/buildhome/.nvm/versions/node/v16.19.0/bin:/opt/buildhome/python2.7/bin:/home/linuxbrew/.linuxbrew/bin:/opt/buildhome/.swiftenv/bin:/opt/buildhome/.swiftenv/shims:/opt/buildhome/.php:/opt/buildhome/.binrc/bin:/opt/buildhome/.deno/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/buildhome/.cask/bin:/opt/buildhome/.gimme/bin:/opt/buildhome/.dotnet/tools:/opt/buildhome/.dotnet:/opt/buildhome/.cargo/bin
3:35:44 PM: ++ export DMD=dmd
3:35:44 PM: ++ DMD=dmd
3:35:44 PM: ++ export DC=dmd
3:35:44 PM: ++ DC=dmd
3:35:44 PM: + dub build
3:35:52 PM: Fetching vibe-core 1.4.3 (getting selected version)...
3:35:52 PM: Fetching memutils 0.4.13 (getting selected version)...
3:35:53 PM: Fetching taggedalgebraic 0.10.11 (getting selected version)...
3:35:54 PM: Fetching dub ~master (getting selected version)...
3:35:55 PM: Fetching vibe-d 0.8.4 (getting selected version)...
3:35:56 PM: Fetching botan-math 1.0.3 (getting selected version)...
3:35:57 PM: Fetching stdx-allocator 2.77.4 (getting selected version)...
3:35:58 PM: Fetching botan 1.12.10 (getting selected version)...
3:35:59 PM: Fetching diet-ng 1.5.0 (getting selected version)...
3:36:00 PM: Fetching openssl 1.1.6+1.0.1g (getting selected version)...
3:36:01 PM: Fetching eventcore 0.8.36 (getting selected version)...
3:36:01 PM: Fetching mir-linux-kernel 1.0.1 (getting selected version)...
3:36:02 PM: Fetching libevent 2.0.2+2.0.16 (getting selected version)...
3:36:03 PM: Fetching libasync 0.8.3 (getting selected version)...
3:36:04 PM: WARNING: A deprecated branch based version specification is used for the dependency dub. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
3:36:04 PM: Selected package vibe-d 0.8.4 does not match the dependency specification >=0.9.0 <0.10.0 (optional) in package dub. Need to "dub upgrade"?
3:36:04 PM: Selected package vibe-d 0.8.4 does not match the dependency specification >=0.9.0 <0.10.0 (optional) in package dub. Need to "dub upgrade"?
3:36:04 PM: Performing "debug" build using /opt/buildhome/dlang/dmd-2.085.0/linux/bin64/dmd for x86_64.
3:36:04 PM: diet-ng 1.5.0: building configuration "library"...
3:36:04 PM: mir-linux-kernel 1.0.1: building configuration "library"...
3:36:04 PM: taggedalgebraic 0.10.11: building configuration "library"...
3:36:04 PM: eventcore 0.8.36: building configuration "epoll"...
3:36:05 PM: stdx-allocator 2.77.4: building configuration "library"...
3:36:06 PM: vibe-core 1.4.3: building configuration "epoll"...
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/core.d(692,70): Deprecation: `std.algorithm.setops.No` is not visible from module `core`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(33,23): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(50,3): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(51,3): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(67,3): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(68,3): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(847,14): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(852,9): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(860,13): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(861,10): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(865,10): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(869,11): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(870,11): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:07 PM: /opt/buildhome/.dub/packages/vibe-core-1.4.3/vibe-core/source/vibe/core/log.d(871,11): Deprecation: `opDot` is deprecated. Use `alias this`
3:36:08 PM: vibe-d:utils 0.8.4: building configuration "library"...
3:36:08 PM: vibe-d:data 0.8.4: building configuration "library"...
3:36:09 PM: vibe-d:crypto 0.8.4: building configuration "library"...
3:36:10 PM: vibe-d:stream 0.8.4: building configuration "library"...
3:36:11 PM: vibe-d:textfilter 0.8.4: building configuration "library"...
3:36:11 PM: vibe-d:inet 0.8.4: building configuration "library"...
3:36:13 PM: vibe-d:tls 0.8.4: building configuration "notls"...
3:36:14 PM: vibe-d:http 0.8.4: building configuration "library"...
3:36:18 PM: dub ~master: building configuration "library-nonet"...
3:36:19 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/stdsumtype.d(260,8): Error: module `std.typecons` import `ReplaceTypeUnless` not found
3:36:19 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/stdsumtype.d(306,9): Error: template instance `ReplaceTypeUnless!(isSumTypeInstance, This, typeof(this), TemplateArgsOf!SumType)` `ReplaceTypeUnless` is not a template declaration, it is a alias
3:36:19 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/stdsumtype.d(314,5): Error: tuple index 0 exceeds 0
3:36:19 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/node.d(142,23): Error: template instance `dub.internal.dyaml.stdsumtype.SumType!(YAMLInvalid, YAMLNull, YAMLMerge, bool, long, real, ubyte[], SysTime, string, Pair[], Node[])` error instantiating
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/buildsettings.d(426,40): Error: template instance `dub.internal.configy.Attributes.ConfigParser!(Flags!(BuildRequirement))` error instantiating
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/buildsettings.d(62,10):        instantiated from here: `Flags!(BuildRequirement)`
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/stdsumtype.d(306,9): Error: template instance `ReplaceTypeUnless!(isSumTypeInstance, This, typeof(this), TemplateArgsOf!SumType)` `ReplaceTypeUnless` is not a template declaration, it is a alias
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/stdsumtype.d(314,5): Error: tuple index 0 exceeds 0
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(46,24): Error: template instance `dub.internal.dyaml.stdsumtype.SumType!(VersionRange, GenericPath!(PosixPathFormat), Repository)` error instantiating
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(218,13): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(221,13): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(224,13): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(227,13): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(234,12): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(397,14): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(298,20): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(362,21): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
3:36:20 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(683,27): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
3:36:20 PM: /opt/buildhome/dlang/dmd-2.085.0/linux/bin64/dmd failed with exit code 1.
3:36:20 PM: ​
3:36:20 PM:   "build.command" failed                                        
3:36:20 PM: ────────────────────────────────────────────────────────────────
3:36:20 PM: ​
3:36:20 PM:   Error message
3:36:20 PM:   Command failed with exit code 2: bash netlify.sh (https://ntl.fyi/exit-code-2)
3:36:20 PM: ​
3:36:20 PM:   Error location
3:36:20 PM:   In build.command from netlify.toml:
3:36:20 PM:   bash netlify.sh
3:36:20 PM: ​
3:36:20 PM:   Resolved config
3:36:20 PM:   build:
3:36:20 PM:     command: bash netlify.sh
3:36:20 PM:     commandOrigin: config
3:36:20 PM:     environment:
3:36:20 PM:       - REVIEW_ID
3:36:20 PM:     publish: /opt/build/repo/out
3:36:20 PM:     publishOrigin: config
3:36:20 PM: Caching artifacts
3:36:20 PM: Started saving build plugins
3:36:21 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
3:36:20 PM: Finished saving build plugins
3:36:20 PM: Started saving pip cache
3:36:20 PM: Finished saving pip cache
3:36:20 PM: Started saving emacs cask dependencies
3:36:20 PM: Finished saving emacs cask dependencies
3:36:20 PM: Started saving maven dependencies
3:36:20 PM: Finished saving maven dependencies
3:36:20 PM: Started saving boot dependencies
3:36:20 PM: Finished saving boot dependencies
3:36:20 PM: Started saving rust rustup cache
3:36:20 PM: Finished saving rust rustup cache
3:36:20 PM: Started saving go dependencies
3:36:20 PM: Finished saving go dependencies
3:36:21 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
3:36:21 PM: Failing build: Failed to build site
3:36:21 PM: Finished processing build request in 51.129748653s
```

**Comment by WebFreak001** [comment]
currently "public domain" is usually used for this, it may be best to work toward implementing https://github.com/dlang/dub/issues/2403

**Comment by s-ludwig** [comment]
Looks like the DMD version on netlify.sh needs to be bumped to 2.100.2 or 2.101.1.

**Review by s-ludwig — CHANGES_REQUESTED** [review]
Should just be `CC0-1.0` instead of just `CC0` to comply with https://spdx.org/licenses/CC0-1.0.html

**Review by s-ludwig — APPROVED** [review]

**Pull request merged**
