### PR TITLE
replace everything with mkdocs (customized material theme)

### LINKED ISSUE #12: Add a "edit this page" button

### LINKED ISSUE #49: Error building docs from diet-ng
I cloned the repo:

    git clone https://github.com/dlang/dub-docs

Then:
```
nick@nmt-pc:~/git/dub-docs$ dub
     Warning Dependency 'dub' depends on git branch '~master', which is deprecated.
             Specify the git repository and commit hash in your dub.sdl:
             dependency "dub" repository="git+<git url>" version="<commit>"
     Warning Selected package vibe-d 0.8.4 does not match the dependency specification >=0.9.0 <0.10.0 in package dub. Need to "dub upgrade"?
     Warning Selected package vibe-d 0.8.4 does not match the dependency specification >=0.9.0 <0.10.0 in package dub. Need to "dub upgrade"?
    Starting Performing "debug" build using /usr/bin/dmd for x86_64.
    Building diet-ng 1.5.0: building configuration [library]
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/defs.d(30,47): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/dom.d(148,31): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/dom.d(380,19): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/html.d(487,45): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/html.d(508,48): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/internal/string.d(41,25): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(636,30): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(637,28): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1262,80): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1306,78): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1343,41): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1343,74): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1360,43): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1360,76): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1377,29): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1377,87): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1416,37): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1484,34): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1484,67): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1521,36): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1521,85): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(751,10): Error: cannot append type `Nullable!(Node[])` to type `Nullable!(Node[])`
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(752,33): Error: cannot append type `diet.dom.Node` to type `Nullable!(Node[])`
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(789,59): Error: function `diet.dom.NodeContent.tag(Node node)` is not callable using argument types `(Node[])`
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(789,59):        cannot pass argument `n` of type `Node[]` to parameter `Node node`
/usr/include/dmd/phobos/std/algorithm/iteration.d(479,16):        instantiated from here: `MapResult!(__lambda4, Nullable!(Node[]))`
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(789,33):        instantiated from here: `map!(Nullable!(Node[]))`
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(1549,20):        instantiated from here: `__lambda19!(NodeContent)`
../../.dub/packages/diet-ng/1.5.0/diet-ng/source/diet/parser.d(785,14):        instantiated from here: `modifyArray!((nc)
{
Nullable!(NodeContent[]) rn;
if (nc.kind == NodeContent.Kind.node)
{
auto mod = processNode(nc.node);
if (!mod.isNull())
rn = mod.map!((n) => NodeContent.tag(n)).array;
}
assert(rn.isNull || rn.get.all!((n) => n.node.name != "block"));
return rn;
}
, NodeContent)`
Error /usr/bin/dmd failed with exit code 1.
nick@nmt-pc:~/git/dub-docs$ git log|head
commit b6e85d3c7a728ab215994da70fd285860b8c7f73
Merge: c35727b 4b76e61
Author: Sönke Ludwig <sludwig@rejectedsoftware.com>
Date:   Sun Dec 25 18:19:40 2022 +0100

    Merge pull request #47 from Moth-Tolias/patch-1
    
    Add CC0 to valid licences
```

### LINKED ISSUE #53: Netlify build failing
see https://app.netlify.com/sites/dub-registry/deploys/64ca7e90e7566200081285e8

```
4:05:34 PM: dub ~master: building configuration library-nonet...
4:05:34 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/stdsumtype.d(260,8): Error: module `std.typecons` import `ReplaceTypeUnless` not found
4:05:34 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/stdsumtype.d(306,9): Error: template instance `ReplaceTypeUnless!(isSumTypeInstance, This, typeof(this), TemplateArgsOf!SumType)` `ReplaceTypeUnless` is not a template declaration, it is a alias
4:05:34 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/stdsumtype.d(314,5): Error: tuple index 0 exceeds 0
4:05:34 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/node.d(142,23): Error: template instance `dub.internal.dyaml.stdsumtype.SumType!(YAMLInvalid, YAMLNull, YAMLMerge, bool, long, real, ubyte[], SysTime, string, Pair[], Node[])` error instantiating
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/buildsettings.d(465,40): Error: template instance `dub.internal.configy.Attributes.ConfigParser!(Flags!(BuildRequirement))` error instantiating
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/buildsettings.d(63,10):        instantiated from here: `Flags!(BuildRequirement)`
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/stdsumtype.d(306,9): Error: template instance `ReplaceTypeUnless!(isSumTypeInstance, This, typeof(this), TemplateArgsOf!SumType)` `ReplaceTypeUnless` is not a template declaration, it is a alias
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/internal/dyaml/stdsumtype.d(314,5): Error: tuple index 0 exceeds 0
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(46,24): Error: template instance `dub.internal.dyaml.stdsumtype.SumType!(VersionRange, GenericPath!(PosixPathFormat), Repository)` error instantiating
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(220,13): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(223,13): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(226,13): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(229,13): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(236,12): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(399,14): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(300,20): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(364,21): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
4:05:35 PM: /opt/buildhome/.dub/packages/dub-master/dub/source/dub/recipe/packagerecipe.d(692,27): Error: `dub.compilers.compiler.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/compilers/compiler.d(11,81) conflicts with `dub.dependency.Dependency` at /opt/buildhome/.dub/packages/dub-master/dub/source/dub/dependency.d(44,1)
4:05:35 PM: /opt/buildhome/dlang/dmd-2.085.0/linux/bin64/dmd failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by WebFreak001**
fix #53, fix #49, fix #12

uses material docs + markdown instead of vibe.d / diet now

mkdocs offers many advantages over the custom diet system we have right now:

- full-text search (offline, with JS)
- many plugins for commonly used functionality on documentation sites (e.g. social graph images / description, "edit this page" / github integration, authors list, last edited time, comments / reviews / also integration through github, etc)
- written in markdown, which has greater editor support, can be more easily looked at without the need to compile, making more people likely to edit the docs
- automatically generated things such as ToC
- full design (light and dark theme, mobile support, transitions)

### CODE REVIEW

**Comment by s-ludwig** [comment]
Why replace the auto-generated command line documentation with manual markdown files here that will easily get out of sync?

**Comment by WebFreak001** [comment]
@s-ludwig fixed

**Comment by s-ludwig** [comment]
I haven't had the chance to look at the details, so I can't submit a proper review. But going an offline generation approach for this sounds like the right call. In fact, I would have done something similar if it weren't for the fact that this started off as a small part of dub-registry.

In case this isn't already the case, something that we should make sure is to leave old URLs intact (ideally including page anchors), as there are plenty of existing links to the docs in forum discussions and GitHub issues.

**Comment by WebFreak001** [comment]
I have added redirects and 2 pages explaining the new page layout when coming from the old advanced usage and json/sdl syntax page

should be all ready to go now, incremental improvements over the future are what are going to make it better anyway, right now it should contain all content that was previously on the dub docs and much more

**Comment by WebFreak001** [comment]
issues have been opened here and links in the docs have been updated, so on deploy they will be up-to-date

**Comment by WebFreak001** [comment]
ping

**Comment by WebFreak001** [comment]
ping

**Comment by adamdruppe** [comment]
i have merge power here if nobody objects by the morning ill just click it

**Comment by adamdruppe** [comment]
Having heard no objections, the motion passes.

**Pull request merged**
