### PR TITLE
Pre/post run commands added

### PR DESCRIPTION
**Pull request by andre2007**

### CODE REVIEW

**Comment by andre2007** [comment]
@thewilsonator This is the documents update related to the pre/post run commands.

**Comment by thewilsonator** [comment]
Thanks. (I don't actually have marge rights here). @s-ludwig

**Comment by s-ludwig** [comment]
Appears that I don't have either ;) @wilzbach

**Comment by wilzbach** [comment]
I can't modify team settings, only @andralex or @CyberShadow can, but this repo should be added to the dub team...

**Comment by andre2007** [comment]
Thanks a lot. The documentation https://code.dlang.org/docs/commandline seems to be very old. Who triggers the update?

**Comment by CyberShadow** [comment]
Added some permissions (hopefully some good ones), hope that helps.

**Comment by thewilsonator** [comment]
Thanks!

**Pull request merged**
