### PR TITLE
document toolchain requirements

### LINKED ISSUE #15: No documentation about toolchainRequirements
The newly added `toolchainRequirements` is not documented. It appeared in the DMD changelog [1].

[1] https://dlang.org/changelog/2.085.0.html#toolchain_requirements

### PR DESCRIPTION
**Pull request by rtbo**
fixes #15
see https://github.com/dlang/dub/pull/1571

### CODE REVIEW

**Comment by wilzbach** [comment]
Build failure looks unrelated. I opened https://github.com/dlang/dub-docs/pull/17 to bump the dmd and dub version used.

**Comment by wilzbach** [comment]
Great, now netlify is being stupid :/ 


```
9:31:00 AM: Starting to prepare the repo for build
9:31:02 AM: git ref pull/16/head does not exist or you do not have permission
9:31:02 AM: failed during stage 'preparing repo': git ref pull/16/head does not exist
9:31:02 AM: Failing build: Failed to prepare repo
```

**Comment by ZombineDev** [comment]
(restarting Netlify)

**Comment by wilzbach** [comment]
I also tried to resubmit the PR (https://github.com/dlang/dub-docs/pull/18), but Netlify doesn't work there either :/

**Comment by wilzbach** [comment]
FYI: I sent out a request to install the Netlify GitHub App here as this might resolve the issue.

**Pull request merged**
